// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-3SmrRIWe58_wxBMCbULyKRrvjwEeT1Q',
    appId: '1:969973538198:web:61c0aac6f2d9f808e7d1b7',
    messagingSenderId: '969973538198',
    projectId: 'roadhaven-eed3e',
    authDomain: 'roadhaven-eed3e.firebaseapp.com',
    storageBucket: 'roadhaven-eed3e.firebasestorage.app',
    measurementId: 'G-SM079N7FTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlX0sTwkUQHObihV11iLoX2GMCgOu65rM',
    appId: '1:969973538198:android:f4ecf8c1813f9912e7d1b7',
    messagingSenderId: '969973538198',
    projectId: 'roadhaven-eed3e',
    storageBucket: 'roadhaven-eed3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByIhKBAz8UXCyBpdYaArvRKXTX_6dXP9A',
    appId: '1:969973538198:ios:68819e311e40b63de7d1b7',
    messagingSenderId: '969973538198',
    projectId: 'roadhaven-eed3e',
    storageBucket: 'roadhaven-eed3e.firebasestorage.app',
    iosBundleId: 'com.example.roadhaven',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByIhKBAz8UXCyBpdYaArvRKXTX_6dXP9A',
    appId: '1:969973538198:ios:68819e311e40b63de7d1b7',
    messagingSenderId: '969973538198',
    projectId: 'roadhaven-eed3e',
    storageBucket: 'roadhaven-eed3e.firebasestorage.app',
    iosBundleId: 'com.example.roadhaven',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-3SmrRIWe58_wxBMCbULyKRrvjwEeT1Q',
    appId: '1:969973538198:web:19e5d7ff8a17b280e7d1b7',
    messagingSenderId: '969973538198',
    projectId: 'roadhaven-eed3e',
    authDomain: 'roadhaven-eed3e.firebaseapp.com',
    storageBucket: 'roadhaven-eed3e.firebasestorage.app',
    measurementId: 'G-651WR7ZM18',
  );
}
